version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: queuejs
      POSTGRES_PASSWORD: queuejs123

  # app:
  #   build: .
  #   restart: always
