# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  prepare:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run pgenerate:test
      - run: npm run pushdb:test
      - save_cache:
          paths:
            - ~/project/node_modules
            - ~/project/prisma/test.db
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
  run-unit-tests:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: Run tests
          command: npm run test

  run-e2e-tests:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: Run tests
          command: npm run test:e2e

workflows:
  run-all-tests:
    jobs:
      - prepare
      - run-unit-tests
